version: '3.8'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_commerce_vol:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'commerce'
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysql_commerce_vol:
